modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "configurable_conflicts"
version = "${version}"
displayName = "ConfigurableConflicts"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''